/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


package my.MIST;
import javax.swing.*;
import java.io.*;

/**
 *
 * @author Joseph Shaffer
 * @version March 20, 2014
 */
public class MISTUI extends javax.swing.JFrame{

    /**
     * Creates new form MISTUI
     */
    public MISTUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        orderGroup = new javax.swing.ButtonGroup();
        repetitionsGroup = new javax.swing.ButtonGroup();
        scannerGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        startButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        loadButton = new javax.swing.JButton();
        restBox = new javax.swing.JCheckBox();
        controlBox = new javax.swing.JCheckBox();
        expBox = new javax.swing.JCheckBox();
        restAcqBox = new javax.swing.JTextField();
        ctrlAcqBox = new javax.swing.JTextField();
        expAcqBox = new javax.swing.JTextField();
        subjIDBox = new javax.swing.JTextField();
        outFileBox = new javax.swing.JTextField();
        outFileButton = new javax.swing.JButton();
        outFileNameBox = new javax.swing.JTextField();
        corrFeedBack = new javax.swing.JTextField();
        inCorrFeedBack = new javax.swing.JTextField();
        recFeedBack = new javax.swing.JTextField();
        notRecFeedBack = new javax.swing.JTextField();
        strictButton = new javax.swing.JRadioButton();
        randomButton = new javax.swing.JRadioButton();
        speedSlider = new javax.swing.JSlider();
        oneButton = new javax.swing.JRadioButton();
        twoButton = new javax.swing.JRadioButton();
        threeButton = new javax.swing.JRadioButton();
        leftResponseBox = new javax.swing.JTextField();
        rightResponseBox = new javax.swing.JTextField();
        confirmResponseBox = new javax.swing.JTextField();
        mouseButton = new javax.swing.JRadioButton();
        kbdButton = new javax.swing.JRadioButton();
        noneButton = new javax.swing.JRadioButton();
        scanKeyBox = new javax.swing.JTextField();
        ctrlTimeoutBox = new javax.swing.JCheckBox();
        nBackBox = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        enableDISDAQBox = new javax.swing.JCheckBox();
        DISDAQAcquisitionsField = new javax.swing.JTextField();
        enableSoundBox = new javax.swing.JCheckBox();
        childVcheckBox = new javax.swing.JCheckBox();
        condDiffSlider = new javax.swing.JSlider();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("MIST Setup"));

        startButton.setMnemonic('a');
        startButton.setText("Start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        saveButton.setText("Save Settings");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        loadButton.setText("Load Settings");
        loadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonActionPerformed(evt);
            }
        });

        restBox.setSelected(true);
        restBox.setText("Rest");
        restBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restBoxActionPerformed(evt);
            }
        });

        controlBox.setSelected(true);
        controlBox.setText("Control");

        expBox.setSelected(true);
        expBox.setText("Experimental");

        restAcqBox.setText("55");

        ctrlAcqBox.setText("55");

        expAcqBox.setText("55");

        subjIDBox.setText("SUBJ0001");

        outFileBox.setText(System.getProperty("user.dir"));
        outFileBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outFileBoxActionPerformed(evt);
            }
        });

        outFileButton.setText("Browse");
        outFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outFileButtonActionPerformed(evt);
            }
        });

        outFileNameBox.setText("SUBJ0001");

        corrFeedBack.setText("CORRECT");
        corrFeedBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                corrFeedBackActionPerformed(evt);
            }
        });

        inCorrFeedBack.setText("INCORRECT");

        recFeedBack.setText("RECORDED");

        notRecFeedBack.setText("NOT RECORDED");

        orderGroup.add(strictButton);
        strictButton.setText("Strict");

        orderGroup.add(randomButton);
        randomButton.setSelected(true);
        randomButton.setText("Randomized");

        speedSlider.setMaximum(8);
        speedSlider.setMinimum(1);
        speedSlider.setValue(7);

        repetitionsGroup.add(oneButton);
        oneButton.setText("1");

        repetitionsGroup.add(twoButton);
        twoButton.setText("2");

        repetitionsGroup.add(threeButton);
        threeButton.setSelected(true);
        threeButton.setText("3");

        leftResponseBox.setText("1");

        rightResponseBox.setText("3");

        confirmResponseBox.setText("2");

        scannerGroup.add(mouseButton);
        mouseButton.setText("Mouse Button");
        mouseButton.setEnabled(false);
        mouseButton.setFocusable(false);

        scannerGroup.add(kbdButton);
        kbdButton.setText("Keyboard Key");

        scannerGroup.add(noneButton);
        noneButton.setSelected(true);
        noneButton.setText("None (time control)");

        scanKeyBox.setText("a");

        ctrlTimeoutBox.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        ctrlTimeoutBox.setText("Control without Timeout");

        nBackBox.setText("0");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Conditions");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Acquisitions/Time");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Subject ID");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("Output Location");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("Feedback Message");

        jLabel6.setText("Correct");

        jLabel7.setText("Incorrect");

        jLabel8.setText("Recorded");

        jLabel9.setText("Not Recorded");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel10.setText("Order of Conditions");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel11.setText("Control Condition Speed");

        jLabel12.setText("Fast");

        jLabel13.setText("Slow");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel14.setText("Repetitions Within");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel15.setText("Response Keys");

        jLabel16.setText("Left");

        jLabel17.setText("Right");

        jLabel18.setText("Confirm");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel19.setText("Scanner Signal");

        jLabel20.setText("N-Back Number");
        jLabel20.setEnabled(false);
        jLabel20.setFocusable(false);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel21.setText("Output Filename");

        enableDISDAQBox.setSelected(true);
        enableDISDAQBox.setText("Count DISDAQs");

        DISDAQAcquisitionsField.setText("6");

        enableSoundBox.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        enableSoundBox.setSelected(true);
        enableSoundBox.setText("Enable Sound");

        childVcheckBox.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        childVcheckBox.setText("Children's Version");
        childVcheckBox.setEnabled(false);
        childVcheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                childVcheckBoxActionPerformed(evt);
            }
        });

        condDiffSlider.setMajorTickSpacing(1);
        condDiffSlider.setMaximum(5);
        condDiffSlider.setPaintTicks(true);
        condDiffSlider.setSnapToTicks(true);
        condDiffSlider.setToolTipText("");

        jLabel24.setText("Diff.");

        jLabel25.setText("Easy");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel26.setText("Experimental Condition Difficulty");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1))
                            .addComponent(restBox)
                            .addComponent(controlBox)
                            .addComponent(expBox))
                        .addGap(2, 2, 2)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(enableDISDAQBox)
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DISDAQAcquisitionsField)
                            .addComponent(restAcqBox, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                            .addComponent(ctrlAcqBox)
                            .addComponent(expAcqBox))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(noneButton)
                            .addComponent(kbdButton)
                            .addComponent(mouseButton)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(51, 51, 51)
                        .addComponent(jLabel14))
                    .addComponent(subjIDBox, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(strictButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(randomButton)
                        .addGap(18, 18, 18)
                        .addComponent(oneButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(twoButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(threeButton))
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(outFileBox, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(outFileButton))
                    .addComponent(jLabel21)
                    .addComponent(outFileNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(speedSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12))
                            .addComponent(jLabel11))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(condDiffSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel24)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(scanKeyBox, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(confirmResponseBox, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(leftResponseBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rightResponseBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel16)
                                .addComponent(jLabel15)
                                .addComponent(jLabel17))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(notRecFeedBack, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(recFeedBack, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(7, 7, 7)
                                .addComponent(nBackBox, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(childVcheckBox)
                                .addComponent(ctrlTimeoutBox)
                                .addComponent(enableSoundBox))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(79, 79, 79))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(saveButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(loadButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(startButton))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(17, 17, 17)
                                .addComponent(corrFeedBack, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(inCorrFeedBack, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(leftResponseBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(rightResponseBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(scanKeyBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel18)
                                .addComponent(confirmResponseBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(1, 1, 1)
                        .addComponent(childVcheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ctrlTimeoutBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(enableSoundBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(nBackBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(corrFeedBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inCorrFeedBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(recFeedBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(notRecFeedBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(startButton)
                            .addComponent(loadButton)
                            .addComponent(saveButton)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(restBox)
                            .addComponent(restAcqBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mouseButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(controlBox)
                            .addComponent(ctrlAcqBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kbdButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(expBox)
                                .addComponent(expAcqBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(noneButton))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(enableDISDAQBox)
                            .addComponent(DISDAQAcquisitionsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(speedSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel12)
                                .addComponent(jLabel25))
                            .addComponent(jLabel13)
                            .addComponent(condDiffSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(threeButton)
                            .addComponent(twoButton)
                            .addComponent(oneButton)
                            .addComponent(randomButton)
                            .addComponent(strictButton))
                        .addGap(5, 5, 5)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subjIDBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel4)
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(outFileBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(outFileButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(outFileNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/MIST/Mist Header.png"))); // NOI18N
        jLabel22.setText("jLabel22");

        jLabel23.setText("Implemented in Java by J. Shaffer 2014, Edits by Josh Bizzell 2016");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
        );

        setSize(new java.awt.Dimension(836, 638));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void restBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_restBoxActionPerformed

    private void outFileBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outFileBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outFileBoxActionPerformed

    private void outFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outFileButtonActionPerformed
        // TODO add your handling code here:
       JFileChooser fc = new JFileChooser();
       fc.setCurrentDirectory(new File("."));
       fc.setApproveButtonToolTipText("Set Output Directory");
    fc.setFileSelectionMode( JFileChooser.DIRECTORIES_ONLY );
    if( fc.showOpenDialog(null) == JFileChooser.APPROVE_OPTION )
    {
        outFileBox.setText(fc.getSelectedFile().getAbsolutePath());
        
    }
    }//GEN-LAST:event_outFileButtonActionPerformed

    private void corrFeedBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_corrFeedBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_corrFeedBackActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        
        //Code to create the RunSettings object implemented when "save" and when "start" buttons are pressed. Saves the various fields into the RunSettings Object
        int order = 1;
        int repetitions = 3;
        int signal = 2;
        if (strictButton.isSelected()) {
            order = 0;
        }
        else if (randomButton.isSelected()){
            order = 1;
        }
        if (oneButton.isSelected()) {
            repetitions = 1;
        }
        else if (twoButton.isSelected()){
            repetitions = 2;
        }
        else if (threeButton.isSelected()){
            repetitions = 3;
        }
      
       if (mouseButton.isSelected()){
           signal = 0;
       }
       else if (kbdButton.isSelected()){
           signal = 1;
       }
       else if (noneButton.isSelected()){
           signal = 2;
       }
       //RunSettings run1 = new RunSettings(restBox.isEnabled(), controlBox.isEnabled(), expBox.isEnabled(), restAcqBox.getText(), ctrlAcqBox.getText(), expAcqBox.getText(), speedSlider.getValue(), order, repetitions, subjIDBox.getText(), outFileBox.getText(), outFileNameBox.getText(), signal, scanKeyBox.getText(), leftResponseBox.getText(), rightResponseBox.getText(), confirmResponseBox.getText(), ctrlTimeoutBox.isSelected(), nBackBox.getText(), corrFeedBack.getText(), inCorrFeedBack.getText(), recFeedBack.getText(), notRecFeedBack.getText(), enableDISDAQBox.isSelected(), DISDAQAcquisitionsField.getText(), enableSoundBox.isSelected(), childVcheckBox.isSelected(), condDiffSlider.getValue());
       RunSettings run1 = new RunSettings(restBox.isSelected(), controlBox.isSelected(), expBox.isSelected(), restAcqBox.getText(), ctrlAcqBox.getText(), expAcqBox.getText(), speedSlider.getValue(), order, repetitions, subjIDBox.getText(), outFileBox.getText(), outFileNameBox.getText(), signal, scanKeyBox.getText(), leftResponseBox.getText(), rightResponseBox.getText(), confirmResponseBox.getText(), ctrlTimeoutBox.isSelected(), nBackBox.getText(), corrFeedBack.getText(), inCorrFeedBack.getText(), recFeedBack.getText(), notRecFeedBack.getText(), enableDISDAQBox.isSelected(), DISDAQAcquisitionsField.getText(), enableSoundBox.isSelected(), childVcheckBox.isSelected(), condDiffSlider.getValue());
       String output = run1.write();
       
       File file = null;
       String path = "";
       
       JFileChooser fc = new JFileChooser();
       fc.setCurrentDirectory(new File("."));
       // Set the text
       fc.setApproveButtonText("Save");
       // Set the mnemonic
       fc.setApproveButtonMnemonic('s');
       // Set the tool tip
       fc.setApproveButtonToolTipText("Save MIST Settings");
     
        if( fc.showOpenDialog(null) == JFileChooser.APPROVE_OPTION )
        {
           file = fc.getSelectedFile();
           path = file.getPath();
        }
       
       try{
       PrintWriter out = new PrintWriter(file);
       out.println(output);
       //System.out.println(output);
       out.close();
                   
       }
       catch(FileNotFoundException fnfe) {
            JOptionPane.showMessageDialog(null, "Please Select a valid file.");
       }
      
      
    }//GEN-LAST:event_saveButtonActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        // TODO add your handling code here:
        int order = 1;
        int repetitions = 3;
        int signal = 2;
        if (strictButton.isSelected()) {
            order = 0;
        }
        else {
            order = 1;
        }
        if (oneButton.isSelected()) {
            repetitions = 1; 
        }
        else if (twoButton.isSelected()){
            repetitions = 2;
        }
        else {
            repetitions = 3;
        }
       if (mouseButton.isSelected()){
           signal = 0;
       }
       else if (kbdButton.isSelected()){
           signal = 1;
       }
       else {
           signal = 2;
       }
       RunSettings run1 = new RunSettings(restBox.isSelected(), controlBox.isSelected(), expBox.isSelected(), restAcqBox.getText(), ctrlAcqBox.getText(), expAcqBox.getText(), speedSlider.getValue(), order, repetitions, subjIDBox.getText(), outFileBox.getText(), outFileNameBox.getText(), signal, scanKeyBox.getText(), leftResponseBox.getText(), rightResponseBox.getText(), confirmResponseBox.getText(), ctrlTimeoutBox.isSelected(), nBackBox.getText(), corrFeedBack.getText(), inCorrFeedBack.getText(), recFeedBack.getText(), notRecFeedBack.getText(), enableDISDAQBox.isSelected(), DISDAQAcquisitionsField.getText(), enableSoundBox.isSelected(), childVcheckBox.isSelected(), condDiffSlider.getValue());
       
       String path = run1.getFilePath() + "\\" +run1.getFileName() + "settings.txt";
       File file = new File(path);
       // If file exists, append a "+" to the file name
       while (file.exists()) {
           path = run1.getFilePath() + "\\" +run1.getFileName() + "+settings.txt";
           run1.setFileName(run1.getFileName()+"+");
           file = new File(path);
        }
       
       file.getParentFile().mkdirs();
       String output = run1.write();
       
       try{
        PrintWriter out = new PrintWriter(file);
        out.println(output);
        //System.out.println(output);
        out.close();
       }
       catch(FileNotFoundException fnfe) {
            JOptionPane.showMessageDialog(null, "Please Select a valid file path.");
       }
       
      startTask(run1);
      
    }//GEN-LAST:event_startButtonActionPerformed
    private void startTask(RunSettings run){
        //Open new window, hide config screen
        TASKUI tsk = new TASKUI(run);
        tsk.setVisible(true);
        this.setVisible(false);
        tsk.requestFocus();
      
        tsk.startTask();
      
    }
    

    
    private void loadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonActionPerformed
        // TODO add your handling code here:
        File file = null;
        String path = "";
        RunSettings run1 = new RunSettings();
       
       JFileChooser fc = new JFileChooser();
       fc.setCurrentDirectory(new File("."));
       fc.setApproveButtonToolTipText("Load MIST Settings");
     
        if( fc.showOpenDialog(null) == JFileChooser.APPROVE_OPTION )
        {
           file = fc.getSelectedFile();
           path = file.getPath();
        }
        
        try {
            String line;
           String in ="";
            BufferedReader br = new BufferedReader(new FileReader(file));
            
            try{
                while ((line = br.readLine()) !=null){
                
                    run1.read(line);
                   
                }
            }
            catch(IOException ioe){
                JOptionPane.showMessageDialog(null, "Problem Reading File");
            }
             
            updateSettings(run1);
           
                    
        }
        catch (FileNotFoundException fnfe){
            JOptionPane.showMessageDialog(null, "File Not Found");
            
        }
   
    }//GEN-LAST:event_loadButtonActionPerformed

    private void childVcheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_childVcheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_childVcheckBoxActionPerformed
    
   //private void updateSettings(RunSettings run){
   public void updateSettings(RunSettings run){
       //restBox.setEnabled((run.getRestEnabled() == 1));
       //controlBox.setEnabled((run.getControlEnabled() == 1));
       //expBox.setEnabled((run.getExperimentalEnabled() == 1));
       restBox.setSelected((run.getRestEnabled() == 1));
       controlBox.setSelected((run.getControlEnabled() == 1));
       expBox.setSelected((run.getExperimentalEnabled() == 1));
       restAcqBox.setText(Integer.toString(run.getRestAcquisitions()));
       ctrlAcqBox.setText(Integer.toString(run.getControlAcquisitions()));
       expAcqBox.setText(Integer.toString(run.getExperimentalAcquisitions()));
       speedSlider.setValue(run.getControlConditionSpeed());
       subjIDBox.setText(run.getSubjID());
       outFileBox.setText(run.getFilePath());
       outFileNameBox.setText(run.getFileName());
       scanKeyBox.setText(run.getScannerKey());
       leftResponseBox.setText(run.getLeftKey());
       rightResponseBox.setText(run.getRightKey());
       confirmResponseBox.setText(run.getConfirmKey());
       ctrlTimeoutBox.setEnabled((run.getControlTimeout() == 1));
       nBackBox.setText(Integer.toString(run.getNBackNum()));
       corrFeedBack.setText(run.getCorrectFeedback());
       inCorrFeedBack.setText(run.getIncorrectFeedback());
       recFeedBack.setText(run.getRecordedFeedback());
       notRecFeedBack.setText(run.getNotRecordedFeedback());
       enableDISDAQBox.setSelected((run.getCountDISDAQs() == 1));
       DISDAQAcquisitionsField.setText(Integer.toString(run.getDISDAQtime()));
       enableSoundBox.setSelected((run.getSoundEnabled() == 1));
       childVcheckBox.setSelected((run.getChildrensVersion() == 1));
       condDiffSlider.setValue(run.getConditionDifficulty());
    
        if (run.getOrderOfConditions() == 0){
                strictButton.setSelected(true);
                randomButton.setSelected(false);
        }
        else if (run.getOrderOfConditions() == 1){
                randomButton.setSelected(true);
                strictButton.setSelected(false);
           
        }
        if (run.getRepetitionsWithin()==1) {
            oneButton.setSelected(true);
            twoButton.setSelected(false);
            threeButton.setSelected(false);
        }
        else if (run.getRepetitionsWithin()==2){
            oneButton.setSelected(false);
            twoButton.setSelected(true);
            threeButton.setSelected(false);
        }
        else if (run.getRepetitionsWithin()==3){
            oneButton.setSelected(false);
            twoButton.setSelected(false);
            threeButton.setSelected(true);
        }
      
       if (run.getScannerSignal() == 0){
           
           mouseButton.setSelected(true);
           kbdButton.setSelected(false);
           noneButton.setSelected(false);
       }
       else if (run.getScannerSignal() == 1){
           mouseButton.setSelected(false);
           kbdButton.setSelected(true);
           noneButton.setSelected(false);
       }
       else if (run.getScannerSignal() == 2){
           mouseButton.setSelected(false);
           kbdButton.setSelected(false);
           noneButton.setSelected(true);
       }
   } 
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MISTUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MISTUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MISTUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MISTUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MISTUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DISDAQAcquisitionsField;
    private javax.swing.JCheckBox childVcheckBox;
    private javax.swing.JSlider condDiffSlider;
    private javax.swing.JTextField confirmResponseBox;
    private javax.swing.JCheckBox controlBox;
    private javax.swing.JTextField corrFeedBack;
    private javax.swing.JTextField ctrlAcqBox;
    private javax.swing.JCheckBox ctrlTimeoutBox;
    private javax.swing.JCheckBox enableDISDAQBox;
    private javax.swing.JCheckBox enableSoundBox;
    private javax.swing.JTextField expAcqBox;
    private javax.swing.JCheckBox expBox;
    private javax.swing.JTextField inCorrFeedBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton kbdButton;
    private javax.swing.JTextField leftResponseBox;
    private javax.swing.JButton loadButton;
    private javax.swing.JRadioButton mouseButton;
    private javax.swing.JTextField nBackBox;
    private javax.swing.JRadioButton noneButton;
    private javax.swing.JTextField notRecFeedBack;
    private javax.swing.JRadioButton oneButton;
    private javax.swing.ButtonGroup orderGroup;
    private javax.swing.JTextField outFileBox;
    private javax.swing.JButton outFileButton;
    private javax.swing.JTextField outFileNameBox;
    private javax.swing.JRadioButton randomButton;
    private javax.swing.JTextField recFeedBack;
    private javax.swing.ButtonGroup repetitionsGroup;
    private javax.swing.JTextField restAcqBox;
    private javax.swing.JCheckBox restBox;
    private javax.swing.JTextField rightResponseBox;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField scanKeyBox;
    private javax.swing.ButtonGroup scannerGroup;
    private javax.swing.JSlider speedSlider;
    private javax.swing.JButton startButton;
    private javax.swing.JRadioButton strictButton;
    private javax.swing.JTextField subjIDBox;
    private javax.swing.JRadioButton threeButton;
    private javax.swing.JRadioButton twoButton;
    // End of variables declaration//GEN-END:variables
}

